# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: opiy.company::lang.testimonial.label

# Model Form Field configuration
form: $/opiy/company/models/testimonial/fields.yaml

# Model Class name
modelClass: Opiy\Company\Models\Testimonial

# Default redirect location
defaultRedirect: opiy/company/testimonials

# Create page
create:
    title: opiy.company::lang.testimonial.create_title
    redirect: opiy/company/testimonials/update/:id
    redirectClose: opiy/company/testimonials

# Update page
update:
    title: opiy.company::lang.testimonial.update_title
    redirect: opiy/company/testimonials
    redirectClose: opiy/company/testimonials

# Preview page
preview:
    title: opiy.company::lang.testimonial.preview_title