# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: opiy.company::lang.employee.label

# Model Form Field configuration
form: $/opiy/company/models/employee/fields.yaml

# Model Class name
modelClass: Opiy\Company\Models\Employee

# Default redirect location
defaultRedirect: opiy/company/employees

# Create page
create:
    title: opiy.company::lang.employee.create_title
    redirect: opiy/company/employees/update/:id
    redirectClose: opiy/company/employees

# Update page
update:
    title: opiy.company::lang.employee.update_title
    redirect: opiy/company/employees
    redirectClose: opiy/company/employees

# Preview page
preview:
    title: opiy.company::lang.employee.preview_title