# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: opiy.company::lang.service.label

# Model Form Field configuration
form: $/opiy/company/models/service/fields.yaml

# Model Class name
modelClass: Opiy\Company\Models\Service

# Default redirect location
defaultRedirect: opiy/company/services

# Create page
create:
    title: opiy.company::lang.service.create_title
    redirect: opiy/company/services/update/:id
    redirectClose: opiy/company/services

# Update page
update:
    title: opiy.company::lang.service.update_title
    redirect: opiy/company/services
    redirectClose: opiy/company/services

# Preview page
preview:
    title: opiy.company::lang.service.preview_title