# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: opiy.company::lang.gallery.label

# Model Form Field configuration
form: $/opiy/company/models/gallery/fields.yaml

# Model Class name
modelClass: Opiy\Company\Models\Gallery

# Default redirect location
defaultRedirect: opiy/company/galleries

# Create page
create:
    title: opiy.company::lang.gallery.create_title
    redirect: opiy/company/galleries/update/:id
    redirectClose: opiy/company/galleries

# Update page
update:
    title: opiy.company::lang.gallery.update_title
    redirect: opiy/company/galleries
    redirectClose: opiy/company/galleries

# Preview page
preview:
    title: opiy.company::lang.gallery.preview_title