# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: opiy.company::lang.tag.label

# Model Form Field configuration
form: $/opiy/company/models/tag/fields.yaml

# Model Class name
modelClass: Opiy\Company\Models\Tag

# Default redirect location
defaultRedirect: opiy/company/tags

# Create page
create:
    title: opiy.company::lang.tag.create_title
    redirect: opiy/company/tags/update/:id
    redirectClose: opiy/company/tags

# Update page
update:
    title: opiy.company::lang.tag.update_title
    redirect: opiy/company/tags
    redirectClose: opiy/company/tags

# Preview page
preview:
    title: opiy.company::lang.tag.preview_title