# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: opiy.company::lang.project.label

# Model Form Field configuration
form: $/opiy/company/models/project/fields.yaml

# Model Class name
modelClass: Opiy\Company\Models\Project

# Default redirect location
defaultRedirect: opiy/company/projects

# Create page
create:
    title: opiy.company::lang.project.create_title
    redirect: opiy/company/projects/update/:id
    redirectClose: opiy/company/projects

# Update page
update:
    title: opiy.company::lang.project.update_title
    redirect: opiy/company/projects
    redirectClose: opiy/company/projects

# Preview page
preview:
    title: opiy.company::lang.project.preview_title