# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: opiy.company::lang.link.label

# Model Form Field configuration
form: $/opiy/company/models/link/fields.yaml

# Model Class name
modelClass: Opiy\Company\Models\Link

# Default redirect location
defaultRedirect: opiy/company/links

# Create page
create:
    title: opiy.company::lang.link.create_title
    redirect: opiy/company/links/update/:id
    redirectClose: opiy/company/links

# Update page
update:
    title: opiy.company::lang.link.update_title
    redirect: opiy/company/links
    redirectClose: opiy/company/links

# Preview page
preview:
    title: opiy.company::lang.link.preview_title